spring:
  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true
  datasource:
    url: jdbc:mariadb://t2.yejin.site:3306/jwtauth__dev?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul
    username: yejin
    password: yejin1234
  jpa:
    hibernate:
      ddl-auto: create